#对外暴露的微服务的实例名
spring:
  application:
    name: eshop-turbine
turbine:
  #指定聚合那些集群，默认为default
  aggregator:
    clusterConfig: default
  #指定了需要收集监控信息的服务名
  appConfig: service-home   
  #指定集群名称
  clusterNameExpression: new String("default")
#指定了服务注册中心的位置
eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/