#对外暴露的微服务实例名
spring: 
  application: 
    name: service-home
  #抽样比例设置为1.0，也就是全部都要采集
  sleuth: 
    sampler: 
      probability: 1.0
#指定服务注册中心的位置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
# 熔断器DashBoard: actuator在boot2.0调整后开关web端点的配置，*代表开启所有
management: 
  endpoints:
    web:
      exposure:
        include: "*"