#对外暴露的微服务实例名
spring:
  application:
    name: service-product
  #采样比例设置为1.0，也就是全部都需要被采集
  sleuth: 
    sampler:
      probability: 1.0
#指定服务注册中心的位置
eureka:
  client:
    service-url: 
      defaultZone: http://127.0.0.1:9000/eureka/